//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBKitaplık.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        public int KitapId { get; set; }
        public string Ad { get; set; }
        public string Sayfa { get; set; }
        public string Yazar { get; set; }
        public Nullable<int> Kategori { get; set; }
    
        public virtual Kategori Kategori1 { get; set; }
    }
}
